// Aidan's Pokemon Card Collection
// Every card uses a direct pokemontcg.io cardId for reliable lookups.
// Cards marked ⚠️ are from sets not yet in the API — show as placeholders.

const CARD_LIST = [
  {
    query: "Bulbasaur 133/132",
    cardId: "me1-133",
    setName: "Mega Evolution",
    tcgUrl: "https://www.tcgplayer.com/product/654472/pokemon-me01-mega-evolution-bulbasaur-133-132",
  },
  {
    query: "Mega Sharpedo ex 113/094",
    cardId: "me2-113",
    setName: "Phantasmal Flames",
    tcgUrl: "https://www.tcgplayer.com/product/662192/pokemon-me02-phantasmal-flames-mega-sharpedo-ex-113-094",
  },
  {
    query: "Whirlipede 133/086",
    cardId: "zsv10pt5-133",
    setName: "Black Bolt",
    tcgUrl: "https://www.tcgplayer.com/product/642588/pokemon-sv-black-bolt-whirlipede-133-086",
  },
  {
    query: "Throh 128/086",
    cardId: "zsv10pt5-128",
    setName: "Black Bolt",
    tcgUrl: "https://www.tcgplayer.com/product/642583/pokemon-sv-black-bolt-throh-128-086",
    imageUrl: "Throh.jpg",
    fallbackPrice: 5.09,
  },
  {
    query: "Rowlet 043",
    cardId: "mep-43",
    setName: "Mega Evolution Promos",
    tcgUrl: "https://www.tcgplayer.com/product/684467/pokemon-me-mega-evolution-promo-rowlet-043?page=1&Language=English",
    imageUrl: "Rowlet.jpg",
    fallbackPrice: 9.80,
  },
  {
    query: "Marill 232/217",
    cardId: "me2pt5-232",
    setName: "Ascended Heroes",
    tcgUrl: "https://www.tcgplayer.com/product/676044/pokemon-me-ascended-heroes-marill-232-217",
    fallbackPrice: 15.00,
  },
  {
    query: "Pidgeotto 208/197",
    cardId: "sv3-208",
    setName: "Obsidian Flames",
    tcgUrl: "https://www.tcgplayer.com/product/509956/pokemon-sv03-obsidian-flames-pidgeotto-208-197",
  },
  {
    query: "Team Rocket's Wobbuffet 203",
    cardId: "svp-203",
    setName: "Scarlet & Violet Black Star Promos",
    tcgUrl: "https://www.tcgcollector.com/cards/49288/team-rockets-wobbuffet-scarlet-and-violet-promos-203",
    fallbackPrice: 9.17,
  },
  {
    query: "Mega Skarmory ex 055/088",
    cardId: "me3-55",
    setName: "Perfect Order",
    tcgUrl: "https://www.tcgplayer.com/product/684351/pokemon-me03-perfect-order-mega-skarmory-ex-055-088",
    fallbackPrice: 1.24,
  },
  {
    query: "Servine 088/086",
    cardId: "zsv10pt5-88",
    setName: "Black Bolt",
    tcgUrl: "https://www.tcgplayer.com/product/642537/pokemon-sv-black-bolt-servine-088-086?Language=English&page=1",
  },
  {
    query: "Dewgong 097/094",
    cardId: "me2-97",
    setName: "Phantasmal Flames",
    tcgUrl: "https://www.tcgplayer.com/product/662152/pokemon-me02-phantasmal-flames-dewgong-097-094?Language=English&page=1",
  },
  {
    query: "Blastoise-EX XY30",
    cardId: "xyp-XY30",
    setName: "XY Black Star Promos",
    tcgUrl: "https://www.tcgplayer.com/product/96393/pokemon-xy-promos-blastoise-ex-xy30?Language=English",
    fallbackPrice: 0.99,
  },
  {
    query: "Salazzle ex 101/088",
    cardId: "me3-101",
    setName: "Perfect Order",
    tcgUrl: "https://www.tcgplayer.com/product/684377/pokemon-me03-perfect-order-salazzle-ex-101-088",
    fallbackPrice: 2.13,
  },
  {
    query: "Tyrunt 070",
    cardId: "mep-70",
    setName: "Mega Evolution Promos",
    tcgUrl: "https://www.tcgplayer.com/product/685562/pokemon-me-mega-evolution-promo-tyrunt-070",
    imageUrl: "Tyrunt.jpg",
    fallbackPrice: 6.41,
  },
  {
    query: "Snorlax 051",
    cardId: "svp-51",
    setName: "Scarlet & Violet Black Star Promos",
    tcgUrl: "https://www.tcgplayer.com/product/517175/pokemon-sv-scarlet-and-violet-promo-cards-snorlax-051",
  },
  {
    query: "Popplio 045",
    cardId: "mep-45",
    setName: "Mega Evolution Promos",
    tcgUrl: "https://www.tcgplayer.com/product/684469/pokemon-me-mega-evolution-promo-popplio-045",
    imageUrl: "Popplio.jpg",
    fallbackPrice: 7.03,
  },
  {
    query: "Mismagius ex 112/094",
    cardId: "me2-112",
    setName: "Phantasmal Flames",
    tcgUrl: "https://www.tcgplayer.com/product/662200/pokemon-me02-phantasmal-flames-mismagius-ex-112-094",
  },
  {
    query: "Mudsdale 175/162",
    cardId: "sv5-175",
    setName: "Temporal Forces",
    tcgUrl: "https://www.tcgplayer.com/product/542896/pokemon-sv05-temporal-forces-mudsdale-175-162",
  },
  {
    query: "Drayton 232/191",
    cardId: "sv8-232",
    setName: "Surging Sparks",
    tcgUrl: "https://www.tcgplayer.com/product/589924/pokemon-sv08-surging-sparks-drayton-232-191",
  },
  {
    query: "Friends in Paldea 137/131",
    cardId: "sv8pt5-137",
    setName: "Prismatic Evolutions",
    tcgUrl: "https://www.tcgplayer.com/product/610492/pokemon-sv-prismatic-evolutions-friends-in-paldea-137-131",
    imageUrl: "Friends.jpg",
    fallbackPrice: 0.99,
  },
  {
    query: "Cheren 258/217",
    cardId: "me2pt5-258",
    setName: "Ascended Heroes",
    tcgUrl: "https://www.tcgplayer.com/product/676070/pokemon-me-ascended-heroes-cheren",
    imageUrl: "https://tcgplayer-cdn.tcgplayer.com/product/676070_in_1000x1000.jpg",
    fallbackPrice: 1.00,
  },
  {
    query: "Ethan's Ho-Oh ex 039/182",
    cardId: "sv10-39",
    setName: "Destined Rivals",
    tcgUrl: "https://www.tcgplayer.com/product/632858/pokemon-sv10-destined-rivals-ethans-ho-oh-ex-039-182",
  },
  {
    query: "Arven's Mabosstiff ex 139/182",
    cardId: "sv10-139",
    setName: "Destined Rivals",
    tcgUrl: "https://www.tcgplayer.com/product/632946/pokemon-sv10-destined-rivals-arvens-mabosstiff-ex-139-182",
  },
  {
    query: "Mewtwo VSTAR GG44/GG70",
    cardId: "swsh12pt5gg-GG44",
    setName: "Crown Zenith: Galarian Gallery",
    tcgUrl: "https://www.tcgplayer.com/product/477057/pokemon-crown-zenith-galarian-gallery-mewtwo-vstar",
  },
  {
    query: "Wigglytuff 105/094",
    cardId: "me2-105",
    setName: "Phantasmal Flames",
  },
  {
    query: "Toxtricity 103/094",
    cardId: "me2-103",
    setName: "Phantasmal Flames",
    imageUrl: "Toxtricity.jpg",
    fallbackPrice: 1.66,
  },
  {
    query: "Dedenne 093/088",
    cardId: "me3-93",
    setName: "Perfect Order",
    imageUrl: "Dedenne.jpg",
    fallbackPrice: 13.42,
  },
  {
    query: "Ethan's Ho-Oh ex 209/182",
    cardId: "sv10-209",
    setName: "Destined Rivals",
  },
  {
    query: "Vulpix 138/132",
    cardId: "me1-138",
    setName: "Mega Evolution",
  },
  {
    query: "Hydrapple 188/182",
    cardId: "sv10-188",
    setName: "Destined Rivals",
    fallbackPrice: 2.54,
  },
  {
    query: "Palossand ex 221/191",
    cardId: "sv8-221",
    setName: "Surging Sparks",
  },
  {
    query: "Gengar 050/088",
    cardId: "me3-50",
    setName: "Perfect Order",
    fallbackPrice: 0.99,
  },
  {
    query: "Mega Froslass ex 265/217",
    cardId: "me2pt5-265",
    setName: "Ascended Heroes",
    imageUrl: "https://tcgplayer-cdn.tcgplayer.com/product/676077_in_1000x1000.jpg",
    fallbackPrice: 17.25,
  },
  {
    query: "Mega Charizard X ex 109/094",
    cardId: "me2-109",
    setName: "Phantasmal Flames",
    tcgUrl: "https://www.tcgplayer.com/product/662183/pokemon-me02-phantasmal-flames-mega-charizard-x-ex-109-094?page=1&Language=English",
    imageUrl: "https://tcgplayer-cdn.tcgplayer.com/product/662183_in_1000x1000.jpg",
  },
  {
    query: "Mega Diancie ex 041/094",
    cardId: "me2-41",
    setName: "Phantasmal Flames",
  },
  {
    query: "Roaring Moon ex 067",
    cardId: "svp-67",
    setName: "Scarlet & Violet Black Star Promos",
    tcgUrl: "https://www.tcgplayer.com/product/527878/pokemon-sv-scarlet-and-violet-promo-cards-roaring-moon-ex-067?page=1&Language=English",
  },
  {
    query: "Mega Mawile ex 162/132",
    cardId: "me1-162",
    setName: "Mega Evolution",
  },
  {
    query: "Lillie's Clefairy ex 056/159",
    cardId: "sv9-56",
    setName: "Journey Together",
    tcgUrl: "https://www.tcgplayer.com/product/623483/pokemon-sv09-journey-together-lillies-clefairy-ex-056-159?page=1&Language=English",
  },
  {
    query: "Ninetales ex 038/165",
    cardId: "sv3pt5-38",
    setName: "Pokemon 151",
  },
  {
    query: "Ludicolo 095/094",
    cardId: "me2-95",
    setName: "Phantasmal Flames",
  },
  {
    query: "Spearow 151/132",
    cardId: "me1-151",
    setName: "Mega Evolution",
  },
  {
    query: "Mega Starmie ex 021/088",
    cardId: "me3-21",
    setName: "Perfect Order",
    fallbackPrice: 17.99,
  },
  {
    query: "Squirtle 007/165",
    cardId: "sv3pt5-7",
    setName: "Pokemon 151",
  },
  {
    query: "Pikachu 088",
    cardId: "svp-88",
    setName: "Scarlet & Violet Black Star Promos",
    tcgUrl: "https://www.tcgplayer.com/product/542481/pokemon-sv-scarlet-and-violet-promo-cards-pikachu-088?page=1&Language=English",
  },
  {
    query: "Mareep GG34/GG70",
    cardId: "swsh12pt5gg-GG34",
    setName: "Crown Zenith: Galarian Gallery",
  },
  {
    query: "Mawile 246/217",
    cardId: "me2pt5-246",
    setName: "Ascended Heroes",
    fallbackPrice: 8.40,
  },
  {
    query: "Mega Charizard Y ex 022/217",
    cardId: "me2pt5-22",
    setName: "Ascended Heroes",
    fallbackPrice: 6.00,
  },
  {
    query: "Mega Charizard X ex 013/094",
    cardId: "me2-13",
    setName: "Phantasmal Flames",
    tcgUrl: "https://www.tcgplayer.com/product/662182/pokemon-me02-phantasmal-flames-mega-charizard-x-ex-013-094?page=1&Language=English",
    imageUrl: "https://tcgplayer-cdn.tcgplayer.com/product/662182_in_1000x1000.jpg",
  },
  {
    query: "Zeraora V 166/198",
    cardId: "swsh6-166",
    setName: "Chilling Reign",
    tcgUrl: "https://www.tcgplayer.com/product/241712/pokemon-swsh06-chilling-reign-zeraora-v-alternate-full-art?page=1&Language=English",
  },
  {
    query: "Mega Lucario ex 113/217",
    cardId: "me2pt5-113",
    setName: "Ascended Heroes",
    imageUrl: "https://i.ebayimg.com/images/g/JokAAeSwmhlpgCN3/s-l1600.webp",
    fallbackPrice: 1.65,
  },
  {
    query: "Garganacl 147/132",
    cardId: "me1-147",
    setName: "Mega Evolution",
  },
  {
    query: "Terapagos ex 180/131",
    cardId: "sv8pt5-180",
    setName: "Prismatic Evolutions",
    imageUrl: "Terapagos.jpg",
    fallbackPrice: 8.26,
  },
  {
    query: "Rowlet 090/088",
    cardId: "me3-90",
    setName: "Perfect Order",
    fallbackPrice: 12.99,
  },
  {
    query: "Litten 044",
    cardId: "mep-44",
    setName: "Mega Evolution Promos",
    imageUrl: "Litten.jpg",
    fallbackPrice: 7.99,
  },
  {
    query: "Ethan's Typhlosion 190/182",
    cardId: "sv10-190",
    setName: "Destined Rivals",
    grade: 8,
  },
  {
    query: "N's Reshiram 167/159",
    cardId: "sv9-167",
    setName: "Journey Together",
    grade: 9,
  },
  {
    query: "Slaking ex 227/191",
    cardId: "sv8-227",
    setName: "Surging Sparks",
    imageUrl: "Slaking.jpg",
    fallbackPrice: 0.89,
  },
  {
    query: "Arcanine ex 032/198",
    cardId: "sv1-32",
    setName: "Scarlet & Violet",
    tcgUrl: "https://www.tcgplayer.com/product/487872/pokemon-sv01-scarlet-and-violet-base-set-arcanine-ex-032-198?page=1&Language=English",
    imageUrl: "https://tcgplayer-cdn.tcgplayer.com/product/487872_in_1000x1000.jpg",
    fallbackPrice: 0.99,
  },
  {
    query: "Gouging Fire ex 144",
    cardId: "svp-144",
    setName: "Scarlet & Violet Black Star Promos",
    tcgUrl: "https://www.tcgplayer.com/product/579993/pokemon-sv-scarlet-and-violet-promo-cards-gouging-fire-ex-144?page=1&Language=English",
  },
  {
    query: "Yanmega ex 003/182",
    cardId: "sv10-3",
    setName: "Destined Rivals",
  },
  {
    query: "Team Rocket's Persian ex 150/182",
    cardId: "sv10-150",
    setName: "Destined Rivals",
  },
  {
    query: "Yveltal ex 053/088",
    cardId: "me3-53",
    setName: "Perfect Order",
    fallbackPrice: 0.99,
  },
  {
    query: "Talonflame 091/088",
    cardId: "me3-91",
    setName: "Perfect Order",
    fallbackPrice: 4.29,
  },
  {
    query: "Thundurus 209",
    cardId: "svp-209",
    setName: "Scarlet & Violet Black Star Promos",
    tcgUrl: "https://www.tcgplayer.com/product/644833/pokemon-sv-scarlet-and-violet-promo-cards-thundurus-209?page=1&Language=English",
    imageUrl: "Thundurus.jpg",
    fallbackPrice: 1.96,
  },
  {
    query: "Brassius 135/131",
    cardId: "sv8pt5-135",
    setName: "Prismatic Evolutions",
  },
  {
    query: "Hydrapple ex 011/131",
    cardId: "sv8pt5-11",
    setName: "Prismatic Evolutions",
  },
  {
    query: "Paras GG32/GG70",
    cardId: "swsh12pt5gg-GG32",
    setName: "Crown Zenith: Galarian Gallery",
  },
  {
    query: "Miraidon ex 081/198",
    cardId: "sv1-81",
    setName: "Scarlet & Violet",
  },
  {
    query: "Iron Leaves ex 176/131",
    cardId: "sv8pt5-176",
    setName: "Prismatic Evolutions",
    tcgUrl: "https://www.tcgplayer.com/product/610531/pokemon-sv-prismatic-evolutions-iron-leaves-ex?page=1&Language=English",
    fallbackPrice: 5.25,
  },
  {
    query: "Team Rocket's Orbeetle 198/182",
    cardId: "sv10-198",
    setName: "Destined Rivals",
  },
  {
    query: "Garganacl 202/182",
    cardId: "sv10-202",
    setName: "Destined Rivals",
  },
  {
    query: "Cramorant 176/167",
    cardId: "sv6-176",
    setName: "Twilight Masquerade",
  },
  {
    query: "Terapagos ex 092/131",
    cardId: "sv8pt5-92",
    setName: "Prismatic Evolutions",
  },
  {
    query: "Mega Latias ex 100/132",
    cardId: "me1-100",
    setName: "Mega Evolution",
  },
  {
    query: "Sandy Shocks ex 056/131",
    cardId: "sv8pt5-56",
    setName: "Prismatic Evolutions",
  },
  {
    query: "Koraidon ex 197",
    cardId: "svp-197",
    setName: "Scarlet & Violet Black Star Promos",
  },
  {
    query: "Chandelure 033/192",
    cardId: "swsh2-33",
    setName: "Rebel Clash",
    tcgUrl: "https://www.tcgplayer.com/product/213109/pokemon-swsh02-rebel-clash-chandelure?page=1&Language=English",
  },
  {
    query: "Regice ex 048/217",
    cardId: "me2pt5-48",
    setName: "Ascended Heroes",
    fallbackPrice: 0.65,
  },
  {
    query: "N's Zoroark ex 058/159",
    cardId: "sv9-58",
    setName: "Journey Together",
  },
  {
    query: "Dudunsparce ex 121/159",
    cardId: "sv9-121",
    setName: "Journey Together",
  },
  {
    query: "Flutter Mane 078/162",
    cardId: "sv5-78",
    setName: "Temporal Forces",
  },
  {
    query: "Hop's Zacian ex 111/159",
    cardId: "sv9-111",
    setName: "Journey Together",
  },
  {
    query: "Veluza ex 043/159",
    cardId: "sv9-43",
    setName: "Journey Together",
  },
  {
    query: "Iron Crown ex 146",
    cardId: "svp-146",
    setName: "Scarlet & Violet Black Star Promos",
    tcgUrl: "https://www.tcgplayer.com/product/579992/pokemon-sv-scarlet-and-violet-promo-cards-iron-crown-ex-146?page=1&Language=English",
  },
  {
    query: "Raging Bolt ex 123/162",
    cardId: "sv5-123",
    setName: "Temporal Forces",
  },
  {
    query: "Iron Thorns ex 077/167",
    cardId: "sv6-77",
    setName: "Twilight Masquerade",
  },
  {
    query: "Dondozo ex 066/182",
    cardId: "sv10-66",
    setName: "Destined Rivals",
  },
  {
    query: "Latios 073/182",
    cardId: "sv10-73",
    setName: "Destined Rivals",
  },
  {
    query: "Team Rocket's Zapdos 070/182",
    cardId: "sv10-70",
    setName: "Destined Rivals",
  },
  {
    query: "Gourgeist 077/203",
    cardId: "swsh7-77",
    setName: "Evolving Skies",
  },
  {
    query: "Gengar 057/198",
    cardId: "swsh6-57",
    setName: "Chilling Reign",
    tcgUrl: "https://www.tcgplayer.com/product/241716/pokemon-swsh06-chilling-reign-gengar?page=1&Language=English",
  },
  {
    query: "Pikachu SWSH234",
    cardId: "swshp-SWSH234",
    setName: "SWSH Black Star Promos",
  },
  {
    query: "Mewtwo 056/172",
    cardId: "tottg-56",
    setName: "Trick or Trade",
    tcgUrl: "https://www.tcgplayer.com/product/283785/pokemon-trick-or-trade-booster-bundle-mewtwo?page=1&Language=English",
    imageUrl: "Mewtwo.jpg",
    fallbackPrice: 0.28,
  },
  {
    query: "Giacomo 138/131",
    cardId: "sv8pt5-138",
    setName: "Prismatic Evolutions",
  },
  {
    query: "Arboliva ex 023/182",
    cardId: "sv10-23",
    setName: "Destined Rivals",
  },
  {
    query: "Okidogi ex 036/064",
    cardId: "sv6pt5-36",
    setName: "Shrouded Fable",
  },
  {
    query: "Kyurem ex 028/086",
    cardId: "zsv10pt5-28",
    setName: "Black Bolt",
  },
  {
    query: "Wigglytuff ex 040/165",
    cardId: "sv3pt5-40",
    setName: "Pokemon 151",
    tcgUrl: "https://www.tcgplayer.com/product/516145/pokemon-sv-scarlet-and-violet-151-wigglytuff-ex-040-165?page=1&Language=English",
  },
  {
    query: "Serperior ex 003/086",
    cardId: "zsv10pt5-3",
    setName: "Black Bolt",
    tcgUrl: "https://www.tcgplayer.com/product/642452/pokemon-sv-black-bolt-serperior-ex?page=1&Language=English",
  },
  {
    query: "Spidops ex 019/198",
    cardId: "sv1-19",
    setName: "Scarlet & Violet",
    tcgUrl: "https://www.tcgplayer.com/product/487856/pokemon-sv01-scarlet-and-violet-base-set-spidops-ex-019-198?page=1&Language=English",
    imageUrl: "Spidops.jpg",
    fallbackPrice: 0.70,
  },
  {
    query: "Incineroar ex 034/162",
    cardId: "sv5-34",
    setName: "Temporal Forces",
    tcgUrl: "https://www.tcgplayer.com/product/542778/pokemon-sv05-temporal-forces-incineroar-ex-034-162?page=1&Language=English",
    fallbackPrice: 0.30,
  },
  {
    query: "Azumarill ex 084/217",
    cardId: "me2pt5-84",
    setName: "Ascended Heroes",
    tcgUrl: "https://www.tcgplayer.com/product/675896/pokemon-me-ascended-heroes-azumarill-ex?page=1&Language=English",
    fallbackPrice: 0.80,
  },
  {
    query: "Tyme 143/131",
    cardId: "sv8pt5-143",
    setName: "Prismatic Evolutions",
  },
  {
    query: "Pikachu 058/102",
    cardId: "base1-58",
    setName: "Base Set",
    price: 5.00,
    grade: 4,
  },
  {
    query: "Charizard V 019/189",
    cardId: "swsh3-19",
    setName: "Darkness Ablaze",
    tcgUrl: "https://www.ebay.com/itm/255036773745",
    fallbackPrice: 38.00,
    grade: 9,
  },
  {
    query: "Charmeleon 005 (Topsun Green Back)",
    setName: "1997 Topsun Japanese",
    imageUrl: "https://i.ebayimg.com/images/g/NSUAAeSw18hn05OV/s-l960.webp",
    price: 15.00,
    grade: 4,
  },
  {
    query: "Meowth (Old Maid)",
    setName: "Japanese Old Maid 2019",
    tcgUrl: "https://www.ebay.com/itm/397772385405",
    imageUrl: "https://i.ebayimg.com/images/g/COcAAeSw3-dpx9Em/s-l1600.webp",
    price: 21.00,
    grade: 10,
  },
  {
    query: "Dark Sylveon V SWSH134",
    cardId: "swshp-SWSH134",
    setName: "SWSH Black Star Promos",
    tcgUrl: "https://www.ebay.com/itm/297959238726",
    price: 13.00,
    grade: 8,
  },
  {
    query: "Alakazam ex 201/165",
    cardId: "sv3pt5-201",
    setName: "Pokemon 151",
    imageUrl: "https://tcgplayer-cdn.tcgplayer.com/product/517047_in_1000x1000.jpg",
    grade: 10,
  },
  {
    query: "Dark Raichu 083/082",
    cardId: "rocket-83",
    setName: "Team Rocket",
    tcgUrl: "https://www.tcgplayer.com/product/84647/pokemon-team-rocket-dark-raichu?page=1&Language=English",
    imageUrl: "https://tcgplayer-cdn.tcgplayer.com/product/84647_in_1000x1000.jpg",
    price: 99.00,
    grade: 7,
  },
  {
    query: "Blaziken 001",
    cardId: "pop1-1",
    setName: "POP Series 1",
    tcgUrl: "https://www.ebay.ca/itm/265153401807",
    price: 499.99,
    grade: 10,
  },
  {
    query: "Team Rocket's Dugtrio 239/217",
    cardId: "me2pt5-239",
    setName: "Ascended Heroes",
    fallbackPrice: 11.69,
  },
  {
    query: "Mega Dragonite 271/217",
    cardId: "me2pt5-271",
    setName: "Ascended Heroes",
    fallbackPrice: 49.70,
  },
  {
    query: "Charmeleon 169/165",
    cardId: "sv3pt5-169",
    setName: "Pokemon 151",
  },
  {
    query: "Bulbasaur 133/132",
    cardId: "me1-133",
    setName: "Mega Evolution",
    tcgUrl: "https://www.tcgplayer.com/product/654472/pokemon-me01-mega-evolution-bulbasaur-133-132",
  },
  {
    query: "Meowth 106/094",
    cardId: "me2-106",
    setName: "Phantasmal Flames",
  },
  {
    query: "Mega Gengar ex 230/193",
    cardId: "m2a-230",
    setName: "High Class Pack Mega Dream EX",
    tcgUrl: "https://www.tcgplayer.com/product/665902/pokemon-japan-m2a-high-class-pack-mega-dream-ex-mega-gengar-ex-230-193?page=1&Language=all",
    imageUrl: "https://tcgplayer-cdn.tcgplayer.com/product/665902_in_1000x1000.jpg",
    fallbackPrice: 26.23,
  },
  {
    query: "Cynthia's Garchomp ex 111/217",
    cardId: "me2pt5-111",
    setName: "Ascended Heroes",
    fallbackPrice: 0.80,
  },
  {
    query: "Single Strike Urshifu vMAX 168/163",
    cardId: "swsh5-168",
    setName: "Battle Styles",
  },
  {
    query: "Elesa's Sparkle 246/172",
    cardId: "swsh12pt5-246",
    setName: "Crown Zenith",
    tcgUrl: "https://www.tcgplayer.com/product/477241/pokemon-crown-zenith-elesas-sparkle-full-art?page=1&Language=English",
    imageUrl: "Elesa.jpg",
    fallbackPrice: 16.95,
  },
  {
    query: "Machamp vMAX 194/198",
    cardId: "swsh10-200",
    setName: "Astral Radiance",
    tcgUrl: "https://www.tcgplayer.com/product/272448/pokemon-swsh10-astral-radiance-machamp-vmax-secret?Language=English&page=1",
  },
  {
    query: "Garchomp & Giratina GX 247/236",
    cardId: "sm11-247",
    setName: "Unified Minds",
    imageUrl: "https://tcgplayer-cdn.tcgplayer.com/product/195140_in_1000x1000.jpg",
    fallbackPrice: 75.00,
  },
  {
    query: "Darkrai GX 088/147",
    cardId: "sm3-88",
    setName: "Burning Shadows",
  },
  {
    query: "Pheromosa & Buzzwole GX 001/173",
    cardId: "sm12a-1",
    setName: "Tag All Stars",
    tcgUrl: "https://www.tcgplayer.com/product/572655/pokemon-japan-sm12a-tag-team-gx-tag-all-stars-pheromosa-and-buzzwole-gx?page=1&Language=all",
    imageUrl: "https://tcgplayer-cdn.tcgplayer.com/product/572655_in_1000x1000.jpg",
    fallbackPrice: 4.74,
  },
  {
    query: "Machamp vMAX 194/189",
    cardId: "swsh3-194",
    setName: "Darkness Ablaze",
  },
  {
    query: "Decidueye GX SV47/SV94",
    cardId: "sm11pt5-SV47",
    setName: "Hidden Fates",
    tcgUrl: "https://www.tcgplayer.com/product/197774/pokemon-hidden-fates-shiny-vault-decidueye-gx?page=1&Language=English",
    imageUrl: "Decidueye.jpg",
    fallbackPrice: 25.19,
  },
  {
    query: "Kartana GX SV65/SV94",
    cardId: "sm11pt5-SV65",
    setName: "Hidden Fates",
    tcgUrl: "https://www.tcgplayer.com/product/197827/pokemon-hidden-fates-shiny-vault-kartana-gx?page=1&Language=English",
    imageUrl: "https://tcgplayer-cdn.tcgplayer.com/product/197827_in_1000x1000.jpg",
    fallbackPrice: 11.40,
  },
];
